version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - sjoerdtalsma
  assignees:
  - sjoerdtalsma
  ignore:
  - dependency-name: org.hibernate.validator:hibernate-validator
    versions:
    - 7.0.0.Final
