sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - graphviz
cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # import the GPG Secret Keys and Ownertrust at the beginning
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "Talsma software CI"
  - git config user.email "travis-ci@talsmasoftware.nl"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper and appropriate settings.xml
  - ./mvnw -s .mvn/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/publish.sh

branches:
  except:
    - /^[0-9]/
