name: Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 8 for compiling Java 5 compatible bytecode
        id: setup-java-8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
          java-package: jdk
      - name: Set up JDK to support jigsaw module system
        id: setup-java-17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Setup maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-repo-
      - name: Perform build
#        run: ./mvnw --batch-mode clean verify sonar:sonar
        run: ./mvnw --batch-mode --settings .github/mvn-settings.xml --global-toolchains .github/mvn-toolchains.xml clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=talsma-ict_enumerables
        shell: bash
        env:
          JAVA_8_HOME: ${{ steps.setup-java-8.outputs.path }}
          JAVA_17_HOME: ${{ steps.setup-java-17.outputs.path }}
